# Lynxii Build Configuration

default:
  image: node:lts
  before_script:
    - npm install --global typescript grunt
    - npm install

# Build
build:
  stage: build
  script:
    - npm run make
  artifacts:
    paths:
      - lib/

# Test
test:
  stage: test
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
  dependencies:
    - build
  script:
    - npm run test
  artifacts:
    paths:
      - lib/
      - coverage/

# Pages
pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
  - master
